server:
  port: ${PORT:8093}
  servlet:
    context-path: /api/order/v1
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:30829/postgresdb}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        generate-ddl: true
  liquibase:
    change-log: classpath:db.changelog/changelog-main.xml
